package com.example.demo.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;


@DynamoDBTable(tableName = "user")
public class UserV2 implements Serializable {
    @DynamoDBHashKey  (attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String first_name;
    @DynamoDBAttribute
    private String last_name;
    @DynamoDBAttribute
    private int total_bill;
    @DynamoDBAttribute
    private int cluster_id;



}