package com.example.demo.entities.V2;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;
import java.io.Serializable;

@DynamoDBTable(tableName = "bill")

public class BillV2 {
    public BillV2(String id, String user_id, LocalDate date, double amount, String type, String number, String location, int month, int label) {
        this.id = id;
        this.user_id = user_id;
        this.date = date.toString();
        this.amount = amount;
        this.type = type;
        this.number = number;
        this.location = location;
        this.month = month;
        this.label = label;
    }

    @DynamoDBHashKey  (attributeName = "id")
    public String getId()
    {
        return id;
    }
    @DynamoDBAutoGeneratedKey
    public String id;

    @DynamoDBAttribute (attributeName="user_id")
    public String getUserId()
    {
        return this.user_id;
    }
    public String user_id;

    @DynamoDBAttribute (attributeName="date")
    public String getDate()
    {
        return this.date;
    }
    public String  date;

    @DynamoDBAttribute (attributeName="amount")
    public double getAmount()
    {
        return this.amount;
    }
    public double amount;

    @DynamoDBAttribute (attributeName="type")
    public String getType()
    {
        return this.type;
    }
    public String type;

    @DynamoDBAttribute (attributeName="number")
    public String getNumber()
    {
        return this.number;
    }
    public String number;

    @DynamoDBAttribute (attributeName="location")
    public String getLocation()
    {
        return this.location;
    }
    public String location;

    @DynamoDBAttribute (attributeName="month")
    public int getMonth()
    {
        return this.month;
    }
    public int month;

    @DynamoDBAttribute (attributeName="label")
    public int getLabel()
    {
        return this.label;
    }
    public int label;
}
