package com.example.demo.entities.V2;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;


@DynamoDBTable(tableName = "electricity_mean_month")
public class ElectricityMeanMonthV2 implements Serializable {
    public ElectricityMeanMonthV2(String id) {
        this.id = id;

    }


    @DynamoDBHashKey  (attributeName = "id")
    public String getId()
    {
        return id;
    }
    @DynamoDBAutoGeneratedKey
    public String id;

    @DynamoDBAttribute (attributeName="electricity_mm1")
    public double getElectricity_mm1()
    {
        return this.electricity_mm1;
    }
    public double electricity_mm1;

    @DynamoDBAttribute (attributeName="electricity_mm2")
    public double getElectricity_mm2()
    {
        return this.electricity_mm2;
    }
    public double electricity_mm2;

    @DynamoDBAttribute (attributeName="electricity_mm3")
    public double getElectricity_mm3()
    {
        return this.electricity_mm3;
    }
    public double electricity_mm3;

    @DynamoDBAttribute (attributeName="electricity_mm4")
    public double getElectricity_mm4()
    {
        return this.electricity_mm4;
    }
    public double electricity_mm4;

    @DynamoDBAttribute (attributeName="electricity_mm5")
    public double getElectricity_mm5()
    {
        return this.electricity_mm5;
    }
    public double electricity_mm5;

    @DynamoDBAttribute (attributeName="electricity_mm6")
    public double getElectricity_mm6()
    {
        return this.electricity_mm6;
    }
    public double electricity_mm6;

    @DynamoDBAttribute (attributeName="electricity_mm7")
    public double getElectricity_mm7()
    {
        return this.electricity_mm7;
    }
    public double electricity_mm7;

    @DynamoDBAttribute (attributeName="electricity_mm8")
    public double getElectricity_mm8()
    {
        return this.electricity_mm8;
    }
    public double electricity_mm8;

    @DynamoDBAttribute (attributeName="electricity_mm9")
    public double getElectricity_mm9()
    {
        return this.electricity_mm9;
    }
    public double electricity_mm9;

    @DynamoDBAttribute (attributeName="electricity_mm10")
    public double getElectricity_mm10()
    {
        return this.electricity_mm10;
    }
    public double electricity_mm10;

    @DynamoDBAttribute (attributeName="electricity_mm11")
    public double getElectricity_mm11()
    {
        return this.electricity_mm11;
    }
    public double electricity_mm11;

    @DynamoDBAttribute (attributeName="electricity_mm12")
    public double getElectricity_mm12()
    {
        return this.electricity_mm12;
    }
    public double electricity_mm12;

    @DynamoDBAttribute (attributeName="user_id")
    public String getUserId()
    {
        return this.user_id;
    }
    public String user_id;
}