package com.example.demo.entities.V2;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;


@DynamoDBTable(tableName = "internet_mean_month")
public class InternetMeanMonthV2 implements Serializable {
    public InternetMeanMonthV2(String id) {
        this.id = id;

    }


    @DynamoDBHashKey  (attributeName = "id")
    public String getId()
    {
        return id;
    }
    @DynamoDBAutoGeneratedKey
    public String id;

    @DynamoDBAttribute (attributeName="internet_mm1")
    public double getInternet_mm1()
    {
        return this.internet_mm1;
    }
    public double internet_mm1;

    @DynamoDBAttribute (attributeName="internet_mm2")
    public double getInternet_mm2()
    {
        return this.internet_mm2;
    }
    public double internet_mm2;

    @DynamoDBAttribute (attributeName="internet_mm3")
    public double getInternet_mm3()
    {
        return this.internet_mm3;
    }
    public double internet_mm3;

    @DynamoDBAttribute (attributeName="internet_mm4")
    public double getInternet_mm4()
    {
        return this.internet_mm4;
    }
    public double internet_mm4;

    @DynamoDBAttribute (attributeName="internet_mm5")
    public double getInternet_mm5()
    {
        return this.internet_mm5;
    }
    public double internet_mm5;

    @DynamoDBAttribute (attributeName="internet_mm6")
    public double getInternet_mm6()
    {
        return this.internet_mm6;
    }
    public double internet_mm6;

    @DynamoDBAttribute (attributeName="internet_mm7")
    public double getInternet_mm7()
    {
        return this.internet_mm7;
    }
    public double internet_mm7;

    @DynamoDBAttribute (attributeName="internet_mm8")
    public double getInternet_mm8()
    {
        return this.internet_mm8;
    }
    public double internet_mm8;

    @DynamoDBAttribute (attributeName="internet_mm9")
    public double getInternet_mm9()
    {
        return this.internet_mm9;
    }
    public double internet_mm9;

    @DynamoDBAttribute (attributeName="internet_mm10")
    public double getInternet_mm10()
    {
        return this.internet_mm10;
    }
    public double internet_mm10;

    @DynamoDBAttribute (attributeName="internet_mm11")
    public double getInternet_mm11()
    {
        return this.internet_mm11;
    }
    public double internet_mm11;

    @DynamoDBAttribute (attributeName="internet_mm12")
    public double getInternet_mm12()
    {
        return this.internet_mm12;
    }
    public double internet_mm12;

    @DynamoDBAttribute (attributeName="user_id")
    public String getUserId()
    {
        return this.user_id;
    }
    public String user_id;
}