package com.example.demo.entities.V2;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;


@DynamoDBTable(tableName = "user_std")
public class UserStdV2 implements Serializable {
    public UserStdV2(String id) {
        this.id = id;

    }


    @DynamoDBHashKey  (attributeName = "id")
    public String getId()
    {
        return id;
    }
    @DynamoDBAutoGeneratedKey
    public String id;

    @DynamoDBAttribute (attributeName="electricity")
    public double getElectricity()
    {
        return this.electricity;
    }
    public double electricity;

    @DynamoDBAttribute (attributeName="internet")
    public double getInternet()
    {
        return this.internet;
    }
    public double internet;

    @DynamoDBAttribute (attributeName="water")
    public double getWater()
    {
        return this.water;
    }
    public double water;

    @DynamoDBAttribute (attributeName="gas")
    public double getGas()
    {
        return this.gas;
    }
    public double gas;

    @DynamoDBAttribute (attributeName="user_id")
    public String getUserId()
    {
        return this.user_id;
    }
    public String user_id;

}