package com.example.demo.entities.V2;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;


@DynamoDBTable(tableName = "water_mean_month")
public class WaterMeanMonthV2 implements Serializable {
    public WaterMeanMonthV2(String id) {
        this.id = id;

    }


    @DynamoDBHashKey  (attributeName = "id")
    public String getId()
    {
        return id;
    }
    @DynamoDBAutoGeneratedKey
    public String id;

    @DynamoDBAttribute (attributeName="water_mm1")
    public double getWater_mm1()
    {
        return this.water_mm1;
    }
    public double water_mm1;

    @DynamoDBAttribute (attributeName="water_mm2")
    public double getWater_mm2()
    {
        return this.water_mm2;
    }
    public double water_mm2;

    @DynamoDBAttribute (attributeName="water_mm3")
    public double getWater_mm3()
    {
        return this.water_mm3;
    }
    public double water_mm3;

    @DynamoDBAttribute (attributeName="water_mm4")
    public double getWater_mm4()
    {
        return this.water_mm4;
    }
    public double water_mm4;

    @DynamoDBAttribute (attributeName="water_mm5")
    public double getWater_mm5()
    {
        return this.water_mm5;
    }
    public double water_mm5;

    @DynamoDBAttribute (attributeName="water_mm6")
    public double getWater_mm6()
    {
        return this.water_mm6;
    }
    public double water_mm6;

    @DynamoDBAttribute (attributeName="water_mm7")
    public double getWater_mm7()
    {
        return this.water_mm7;
    }
    public double water_mm7;

    @DynamoDBAttribute (attributeName="water_mm8")
    public double getWater_mm8()
    {
        return this.water_mm8;
    }
    public double water_mm8;

    @DynamoDBAttribute (attributeName="water_mm9")
    public double getWater_mm9()
    {
        return this.water_mm9;
    }
    public double water_mm9;

    @DynamoDBAttribute (attributeName="water_mm10")
    public double getWater_mm10()
    {
        return this.water_mm10;
    }
    public double water_mm10;

    @DynamoDBAttribute (attributeName="water_mm11")
    public double getWater_mm11()
    {
        return this.water_mm11;
    }
    public double water_mm11;

    @DynamoDBAttribute (attributeName="water_mm12")
    public double getWater_mm12()
    {
        return this.water_mm12;
    }
    public double water_mm12;

    @DynamoDBAttribute (attributeName="user_id")
    public String getUserId()
    {
        return this.user_id;
    }
    public String user_id;
}